### PR TITLE
Finished mastermind

### PR DESCRIPTION
**Pull request by AsadbekAstrum**

### CODE REVIEW

**Review by simple-lemon — CHANGES_REQUESTED** [review]
```
int main(int argc, char *argv[]) {
    char secret_code[5] = "1123";
```
have you read the description ?? 
you should generate secret code.
why your program accepts duplicates on the input?
ctrl + D , isnt working too!!  
pls ckeck your code before submitting.

**Comment by simple-lemon** [comment]
Status - plagiarism 
You should come to the mentor's room within 5 days to complete the essential task to prove that you don't plagiarize, or it will be counted as plagiarism

**Comment by AsadbekAstrum** [comment]
so sorry , I will edit it and re-send

**Comment by simple-lemon** [comment]
siz mentorlar xonasiga kelishingiz kerak 5 kun ichida sizda chiting aniqlangan. agar 5 kun ichida kelmasangiz avtomat tarszda chiting hisoblanadi.

**Pull request closed without merging**
