### PR TITLE
Shukurullo burxonov

### PR DESCRIPTION
**Pull request by burxonovsh**

### CODE REVIEW

**Review by simple-lemon — CHANGES_REQUESTED** [review]
20 qatordan kop kod yozish mumkin emas , uzog'i 23 - 24 qator bolishi mumkin. 
kodiz xato ishlayapti :
```
@simple-lemon ➜ /workspaces/arc-01-my_mastermind (shukurullo-burxonov) $ ./my_mastermind -c 4321 -t 4
Will you find the secret code?
Please enter a valid guess
---
Round 0
>1234
Well placed pieces: 0
Misplaced pieces: 4
---
Round 1
>4312
Well placed pieces: 2
Misplaced pieces: 0
---
Round 2
>43215
Well placed pieces: 4
Misplaced pieces: -4
Congrats! You did it!
@simple-lemon ➜ /workspaces/arc-01-my_mastermind (shukurullo-burxonov) $ 
```
bundan tashqari kodingizda ishlatish mumkin bolmagan funcsiyalar ishlatilgan!!!
Dushanba kuni soat 9 - 10 lada mentorlar xonasiga kelib keting

**Comment by burxonovsh** [comment]
> 20 qatordan kop kod yozish mumkin emas , uzog'i 23 - 24 qator bolishi mumkin. 
> 
> kodiz xato ishlayapti :
> 
> ```
> 
> @simple-lemon ➜ /workspaces/arc-01-my_mastermind (shukurullo-burxonov) $ ./my_mastermind -c 4321 -t 4
> 
> Will you find the secret code?
> 
> Please enter a valid guess
> 
> ---
> 
> Round 0
> 
> >1234
> 
> Well placed pieces: 0
> 
> Misplaced pieces: 4
> 
> ---
> 
> Round 1
> 
> >4312
> 
> Well placed pieces: 2
> 
> Misplaced pieces: 0
> 
> ---
> 
> Round 2
> 
> >43215
> 
> Well placed pieces: 4
> 
> Misplaced pieces: -4
> 
> Congrats! You did it!
> 
> @simple-lemon ➜ /workspaces/arc-01-my_mastermind (shukurullo-burxonov) $ 
> 
> ```
> 
> bundan tashqari kodingizda ishlatish mumkin bolmagan funcsiyalar ishlatilgan!!!
> 
> Dushanba kuni soat 9 - 10 lada mentorlar xonasiga kelib keting

Hop abeddan keyin kirsam boladimi ertalab darslarm bor edi

**Comment by simple-lemon** [comment]
9 da darsiz bormi ?? 9 da keling bomasa , agar ertalab kelomasez soat 2 da keling

**Comment by burxonovsh** [comment]
> 9 da darsiz bormi ?? 9 da keling bomasa , agar ertalab kelomasez soat 2 da keling

2 laga borama unda ertalab boshqa darslarim bor

**Pull request closed without merging**
