### PR TITLE
added all files [main.c readme.md makefile]

### PR DESCRIPTION
**Pull request by bulkset**
with comments )

### CODE REVIEW

**Review by simple-lemon — CHANGES_REQUESTED** [review]
It seems that your code currently accepts inputs outside the specified range. As per the project requirements, only values from 0 to 8 should be accepted, and the input size should strictly be 4 characters. To ensure adherence to project guidelines and enhance the user experience, robust input validation is essential. Inputs such as '9' or '1123' should be considered invalid, and the game should not progress to the next round when such inputs are encountered.
Before submitting your project, it's vital to thoroughly test and run it to ensure it aligns perfectly with the project specifications and functions seamlessly. This step is crucial to eliminate any potential issues and enhance the overall functionality of your project.

**Comment by bulkset** [comment]
fixed !

**Review by simple-lemon — CHANGES_REQUESTED** [review]
plagiarism detected
Your project's review has been rejected!
You should come to the mentor's room within 5 days to complete the essential task to prove that you don't plagiarize, or it will be counted as plagiarism

**Review by simple-lemon — COMMENTED** [review]
```

**Review by simple-lemon — CHANGES_REQUESTED** [review]
```
$ ./myMastermindGame 
Secret Code: 7541
Attempts: 10
Will you find the secret code?
Please enter a valid guess.
Round 0
7531
>Well placed pieces: 3
Misplaced pieces: 0
Round 1
```

**Review by simple-lemon — CHANGES_REQUESTED** [review]
you changed only attempts 
but all other bugs are not fixed 
1) ctrl + D (should stop the game)
2) prompt ">" symbol should be before input 
and user interface shouldn't be cuztomized like "You didn't find the secret code. Try again!" its not required!

**Comment by bulkset** [comment]
fixed

**Review by simple-lemon — APPROVED** [review]
good code

**Pull request closed without merging**
