### PR TITLE
POYONOV_O'RALBEK

### PR DESCRIPTION
**Pull request by Uralbek-2004**

### CODE REVIEW

**Comment by rahmonali077** [comment]
Status - plagiarism
You should come to the mentor's room within 5 days to complete the essential task to prove that you don't plagiarize, or it will be counted as plagiarism

**Comment by simple-lem0n** [comment]
Status - plagiarism
You should come to the mentor's room within 5 days to complete the essential task to prove that you don't plagiarize, or it will be counted as plagiarism
from murod

**Comment by Uralbek-2004** [comment]
Tekshirib bering iltmos

**Review by simple-lemon — APPROVED** [review]
Good code

**Pull request closed without merging**
