### PR TITLE
Raxmonali abduvaliyev

### PR DESCRIPTION
**Pull request by rahmonali077**
Xatolarini tog'irladim va ortiqcha funksiyalarni olib tashladim

### CODE REVIEW

**Comment by UzCoderOff** [comment]
good code

**Comment by UzCoderOff** [comment]
Status - plagiarism
You should come to the mentor's room within 5 days to complete the essential task to prove that you don't plagiarize, or it will be counted as plagiarism
from Komronbek KOMILJONOV

**Comment by simple-lemon** [comment]
branch ga ism familya yozilishi shart deyilmaganmidi ?

**Review by simple-lemon — APPROVED** [review]
good code

**Pull request closed without merging**
