### PR TITLE
Success

### PR DESCRIPTION
**Pull request by 1cLeo**
Good Afternoon! Im so sorry that i lately changed my project it's because of I and my family got out of city to celebrate the NEW YEAR ! 

- I successfully changed my branch name as you said and upgraded my pull request ! 

By the way , Happy New Year ! Thank You !

### CODE REVIEW

**Review by simple-lemon — CHANGES_REQUESTED** [review]
Pls create Branch with your Full name 
i think " 1cLeo:Asadbekk02 " is not your fullname

**Comment by 1cLeo** [comment]
full name ? Asadbek buriev 

I dont understand why you are asking for it , inasmuch as everybody's branch is (name + numbers).

I did my project and i posted it .

**Comment by simple-lemon** [comment]
Mentorskiyga kelib keting. Sizga tushuntirib beraman nimagaligini.

**Comment by 1cLeo** [comment]
Йо майли боршгаку бораман лекн ман branch ни full_name га озгартрсам тогри боладими хаммаси ?

**Pull request closed without merging**
