### PR TITLE
my_mastermind

### PR DESCRIPTION
**Pull request by GlitchLxrd**

### CODE REVIEW

**Comment by GlitchLxrd** [comment]
[README.md](https://github.com/simple-lemon/arc-01-my_mastermind/files/13589460/README.md)
i forgot to add README in the pull request

**Review by simple-lemon — CHANGES_REQUESTED** [review]
I would like to emphasize the importance of including the README file in your code repository. A well-written README is a crucial component of your project, providing essential information to users, contributors, and reviewers. Please make sure to include the README file in your code repository and ensure it is up to date and well-written.

**Comment by GlitchLxrd** [comment]
I've just commited the readme file, check it please.

**Review by simple-lemon — CHANGES_REQUESTED** [review]
Your README file provides a good foundation, but I recommend enhancing it to maintain a more professional tone. Regardless of your experience level in C, a well-structured and informative README can significantly improve the overall impression of your project.

I've noticed that currently, when a user enters a code, the program doesn't provide any feedback. This is an important aspect to address for enhancing the user experience.
```
When the user enters an invalid code, you must respect the following format:
Well placed pieces: X
Misplaced pieces: Y
```
It seems that your code currently accepts inputs outside the specified range. As per the project requirements, only values from 0 to 8 should be accepted, and the input size should strictly be 4 characters. To ensure adherence to project guidelines and enhance the user experience, robust input validation is essential. Inputs such as '9' or '1123' should be considered invalid, and the game should not progress to the next round when such inputs are encountered.

And about your Makefile.mak , its not working. 

Your algorithm demonstrates promise and potential. With continued effort and refinement, it has the potential to yield excellent results. Continue to put in your best effort, and it will yield a good outcome.

Before submitting your project, it's vital to thoroughly test and run it to ensure it aligns perfectly with the project specifications and functions seamlessly. This step is crucial to eliminate any potential issues and enhance the overall functionality of your project.

**Pull request closed without merging**
