### PR TITLE
Ziyoda yoldoshxojayeva

### PR DESCRIPTION
**Pull request by YoldoshxojayevaZiyoda**

### CODE REVIEW

**Review by simple-lemon — CHANGES_REQUESTED** [review]
Status - plagiarism 
You should come to the mentor's room within 5 days to complete the essential task to prove that you don't plagiarize, or it will be counted as plagiarism

**Comment by YoldoshxojayevaZiyoda** [comment]
Assalomu aleykum ustoz   murabbiy xonasida sizga topshiramizmi boshqa mentorlagami

**Comment by simple-lemon** [comment]
vaalaykumassalam, manga topshirasiz

**Comment by YoldoshxojayevaZiyoda** [comment]
Assalomu aleykum  ustoz sizi topolmayapmanu mentorlani xonasida ham yo ekansiz

**Comment by simple-lemon** [comment]
qattasiz hozir

**Comment by YoldoshxojayevaZiyoda** [comment]
Astrumdaman hozitr

**Comment by simple-lemon** [comment]
keling hozir

**Comment by simple-lemon** [comment]
Write a function my_union that takes two strings and returns, without doubles, the
characters that appear in either one of the strings.
char* my_union(char* param_1, char* param_2)
{

}
Example 00

Input: "zpadinton" && "paqefwtdjetyiytjneytjoeyjnejeyj"
Output: 
Return Value: "zpadintoqefwjy"

Example 01

Input: "ddf6vewg64f" && "gtwthgdwthdwfteewhrtag6h4ffdhsd"
Output: 
Return Value: "df6vewg4thras"

Example 02

Input: "rien" && "cette phrase ne cache rien"
Output: 
Return Value: "rienct phas"

**Comment by YoldoshxojayevaZiyoda** [comment]
Ustoz mastermindni git hubdan jonatolmadimde ertaga topshirsam boladimi vohli

**Comment by YoldoshxojayevaZiyoda** [comment]
githubdan hali tasholmadm kodni lkn tayyor kod 
makefile mastermind readme ham

**Pull request closed without merging**
