### PR TITLE
Saidalosaidvosilov

### PR DESCRIPTION
**Pull request by saidalosaidvosilov**
This project completed by Saida'lo Saidvosilov

### CODE REVIEW

**Review by simple-lemon — CHANGES_REQUESTED** [review]
```
char* new_strcpy(char* param_1, char* param_2)
{
    int i = 0;
    for (; param_1[i] != '\0'; i++) {
        param_1[i] = param_2[i];
    }
    return param_1;
}
```
The loop checks for the end of param_1 (param_1[i] != '\0'), but it should be checking for the end of param_2 instead. The function is intended to copy from param_2 to param_1, so the loop should continue until the end of param_2 is reached.
The function does not explicitly copy the null terminator ('\0') from param_2 to param_1. This should be done to ensure param_1 is properly null-terminated after the copying.

Your code doesnt check the second option that entered from argv.
overall good code, just be more careful

**Comment by saidalosaidvosilov** [comment]
Update my_mastermind.c & Fixed the requested changes

**Review by simple-lemon — CHANGES_REQUESTED** [review]
Your code still doesnt check the second option that entered from argv.
if i send 
```
./my_mastermind -t 2 -c 1234
```
it takes only first argument

**Comment by saidalosaidvosilov** [comment]
requested changes fixed!

**Review by simple-lemon — APPROVED** [review]
good code

**Pull request closed without merging**
