### PR TITLE
Mirzoavaz

### PR DESCRIPTION
**Pull request by Number1ava**

### CODE REVIEW

**Review by simple-lemon — CHANGES_REQUESTED** [review]
It seems that your code currently accepts inputs outside the specified range. As per the project requirements, only values from 0 to 8 should be accepted, and the input size should strictly be 4 characters. To ensure adherence to project guidelines and enhance the user experience, robust input validation is essential. Inputs such as '9' or '1123' should be considered invalid, and the game should not progress to the next round when such inputs are encountered.

your Makefile is not working pls check the code before submitting

**Comment by simple-lemon** [comment]
your Readme is not filled correctly
check this site for more information about README https://www.makeareadme.com/

**Comment by Number1ava** [comment]
I did some changes in 3 files

**Review by simple-lemon — CHANGES_REQUESTED** [review]
It seems that your code currently accepts inputs outside the specified range. As per the project requirements, only values from 0 to 8 should be accepted, and the input size should strictly be 4 characters. To ensure adherence to project guidelines and enhance the user experience, robust input validation is essential. Inputs such as '9' or '1123' should be considered invalid, and the game should not progress to the next round when such inputs are encountered.
And project should stop when i press Ctrl + D

**Pull request closed without merging**
